# Generated by Django 6.0.5 on 2026-05-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('duration_minutes', models.IntegerField()),
                ('age_rating', models.IntegerField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/')),
                ('genres', models.ManyToManyField(related_name='movies', to='genre.genre')),
            ],
            options={
                'db_table': 'movies',
                'ordering': ['id'],
            },
        ),
    ]
