# Generated by Django 6.0.5 on 2026-06-01 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.IntegerField(default=1)),
                ('columns', models.IntegerField(default=1)),
                ('projection_type', models.CharField(max_length=50)),
                ('accessibility', models.BooleanField(default=False)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='cinema.cinema')),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['id'],
            },
        ),
    ]
