# Generated by Django 6.0.5 on 2026-05-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_options_remove_room_capacity_room_columns_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='room',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='room',
            name='rows',
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='projection_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
    ]
