# Generated by Django 6.0.5 on 2026-05-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_room_options_remove_room_columns_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.AddField(
            model_name='room',
            name='columns',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='rows',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='projection_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='room',
            table=None,
        ),
    ]
