# Generated by Django 6.0.4 on 2026-05-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='teste@teste.com', max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
