# Generated by Django 6.0.5 on 2026-06-01 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.person')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('cpf', models.CharField(max_length=11)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['id'],
            },
            bases=('person.person',),
        ),
    ]
