# Generated by Django 6.0.5 on 2026-05-27 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending_seats', 'Pending seats'), ('pending_payment', 'Pending payment'), ('pending_approval', 'Pending approval'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_seats', max_length=30)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='client.client')),
                ('screening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='screening.screening')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['id'],
            },
        ),
    ]
