# Generated by Django 6.0.5 on 2026-05-27 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remove_orders_with_invalid_client(apps, schema_editor):
    Order = apps.get_model('order', 'Order')
    Client = apps.get_model('client', 'Client')
    valid_ids = set(Client.objects.values_list('pk', flat=True))
    Order.objects.exclude(client_id__in=valid_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(remove_orders_with_invalid_client, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='client.client'),
        ),
    ]
