# Generated by Django 6.0.5 on 2026-05-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_options_and_more'),
        ('payment', '0002_alter_payment_transaction_status'),
        ('payment', '0002_simplify_payment'),
    ]

    operations = [
    ]
