# Generated by Django 6.0.5 on 2026-05-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_merge_20260528_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_status',
            field=models.CharField(default='pendente', max_length=100),
        ),
    ]
